### ISSUE TITLE
multiple ChucK VMs in Unreal is unstable

### ISSUE THREAD

**Issue by gewang** [ccrma/chunreal#1]
instancing multiple ChucK (VM/main) instances in Chunreal is unstable. It appears capable of running with audio, but will crash. Possibilities:
1) bug with certain global variables shared across VMS (something that Jack and I didn't catch in numchucks; or something added since)
2) there is still occasionally a bad memory dealloc upon ChucK VM **cleanup** it is possible when any VM is deleted, it may be corrupting memory. Need to investigate ChucK deallocation starting with ChucK::~ChucK() with logging enabled etc.
3) a bug we may have introduced during #chureal refactor

**Comment by gewang** [comment]
do we feel confident enough to close this, as least for now? @eitomurakami

**Comment by eitomurakami** [comment]
Yes I think so! Closing now @gewang
