### ISSUE TITLE
SndBuf not supported

### ISSUE THREAD

**Issue by eitomurakami** [ccrma/chunreal#3]
SndBuf isn't supported as a UGen type in Chunreal.

**Comment by gewang** [comment]
hmm, this definitely should be possible, though we might have disabled due to incompatibilities between our libsndfile code and UE5? what happens when `PublicDefinitions.Add("__DISABLE_SNDBUF__");` is removed from Chunreal.Build.cs?

**Comment by eitomurakami** [comment]
Fully functional on MacOS. Importing a .wav file causes a system error on Windows 11.

**Comment by eitomurakami** [comment]
@gewang The error looks something like this on Windows 11, UE 5.3.

```
LogChunreal: "1.5.2.5 (chai)" :(string)
LogChunreal: [chuck](via SndBuf): sndfile error '1' opening 'full_path_to_soundfile.wav'...
LogChunreal: [chuck](via SndBuf): ...(reason: System error : T)
```

**Comment by eitomurakami** [comment]
We found that issue was related to compiling with UNICODE-enabled compilation on Windows; SndBuf (more specifically libsndfile) has been modified to explicitly treat filename as ANSI, for now (we may or not look at UNICODE support in the future).
Thanks to @Amir-BK for tracking down the cause of this issue.
